export enum API_URL {
  CREATE_USER = "auth",
  CREATE_POST = "post/create-post",
  CREATE_PRODUCT = "product",
  CREATE_CATEGORY = "category/new",
  CREATE_PRODUCT_CATEGORY = "prod-category",
  GET_USERS = "auth",
  GET_USER = "auth",
  GET_ALL_POSTS = "post/get",
  GET_SINGLE_POST = "post/get",
  GET_ALL_PRODUCTS = "product/products",
  GET_PRODUCT_BY_ID = "product",
  GET_ALL_CATEGORIES = "category/all",
  GET_HIGHLIGHTED_POSTS = "post/highlighted",
  GET_PRODUCT_CATEGORIES = "prod-category/categories",
  GET_POSTS_BY_CATEGORY = "post/category",
  GET_USER_POSTS = "post/get/userposts",
  UPDATE_PRODUCT = "product",
  UPDATE_USER = "auth",
  DELETE_PRODUCT = "product",
  DELETE_CATEGORY = "category",
  DELETE_PRODUCT_CATEGORY = "prod-category",
}
